### ISSUE TITLE
开发日志

### ISSUE THREAD

**Issue by xohozu** [UTSZ/Bookcase#32]
- 2015-8-16 Beta版终于KO了，购买了苹果开发者账号（好贵的说），目前正在等待审核，希望顺利#_#。
- 2015-8-18 最近看了一些OC相关的博文，包括Runtime、ViewController精简等话题，决定继续完善功能的同时改进/重构代码。（代码目前真的很捉急XD）

**Comment by huangzhemin** [comment]
产品要上线了，是一种什么样的心情
